### ISSUE TITLE
Vaultwarden in broken state, with no logs or errors

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/vaultwarden-wrapper#16]
For an unknown amount of time (probably about a week) my Vaultwarden server was not available at its onion address: the browser would return "Problem Loading Onionsite" and no Bitwarden apps or plugins could connect to it. The local address was similarly unavailable.

During this time, Vaultwarden was displaying status "running", health check "success", and it had zero logs (just the "load more" button), and it fired no notifications.

**A simple stop and start of the service fixed it**, but I figured it might be good to document. :man_shrugging: 

EmbassyOS: 0.3.0~2
Vaultwarden: 1.22.2

**Comment by kn0wmad** [comment]
Thank you for the bug report.  Did you happen to notice anything in the Kernal or OS logs that may be related?

**Comment by spencerflagg** [comment]
Nope, sorry, although I probably didn't go back far enough in the logs to when the problem started.

**Comment by ProofOfKeags** [comment]
Thanks for the documentation. This doesn't give us a lot to go on. At minimum we can audit the health check and see if there's an obvious way to improve it. Ultimately this bug is probably in vaultwarden itself so it may take a while to track down or may just mysteriously disappear on an update to vaultwarden.

**Comment by chrisguida** [comment]
Thanks for the report. I believe I did actually hit this bug myself once.
