### ISSUE TITLE
Add support for alpine like we had on armv7

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/vaultwarden-wrapper#9]
Reported by: @chrisguida

**Comment by elvece** [comment]
@chrisguida could you elaborate on what is desired from this ticket?

**Comment by ProofOfKeags** [comment]
Currently the vaultwarden image is based on debian:buster:

https://github.com/dani-garcia/vaultwarden/blob/175f2aeace6a6099cb3ea47d2de9968e764b5f43/docker/arm64v8/Dockerfile#L110

The request is to move to alpine to save on space. I'm not sure that the tradeoff is worth it though. In exchange for size we incur an indefinite maintenance cost since the official published image is not Alpine. We are experiencing that currently with C-Lightning right now and I'm not sure at our current staffing levels we should be making any changes that incur maintenance costs if we can avoid them.

**Comment by chrisguida** [comment]
Doubt armv8 will be as troublesome as armv7

**Comment by ProofOfKeags** [comment]
I might even lower it to P3. It doesn't matter if it's less troublesome. The issue is that we'd be responsible for maintaining it in perpetuity. We're already very bandwidth constrained. I'd say that unless you can get it upstreamed it isn't worth it *at all*

**Comment by MattDHill** [comment]
This a thing @elvece ?

**Comment by elvece** [comment]
No we use the official supported image now.

**Comment by chrisguida** [comment]
I use debian on a bunch of stuff too now. Eventually once all the dust settles, I'll go back through all our images and make them smaller
